# openapi.yaml
openapi: 3.0.0
info:
  title: Simple API
  version: v1
servers:
  - url: http://localhost:9080
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Hello, world!